export const EVENTS = [
  {
    id: 'tnjfjsanhri-req',
    protocol: 'http',
    requestId: 'tnjfjsanhri',
    timestamp: 1754640493250,
    method: 'GET',
    url: 'http://localhost:64436/socket.io/?EIO=4&transport=polling&t=jn9he0m9',
    headers: {
      Accept: '*/*',
    },
  },
  {
    id: '2fy8illlonc-req',
    protocol: 'http',
    requestId: '2fy8illlonc',
    timestamp: 1754640493251,
    method: 'GET',
    url: 'http://localhost:64436/socket.io/?EIO=4&transport=polling&t=jn9he0m9',
    headers: {
      Accept: '*/*',
    },
  },
  {
    id: 's2xve134evj-req',
    protocol: 'http',
    requestId: 's2xve134evj',
    timestamp: 1754640493259,
    method: 'GET',
    url: 'http://localhost:64436/socket.io/?EIO=4&transport=polling&t=jn9hn3s5&sid=5ZP0tYVNRx34yengAAAI',
    headers: {
      Accept: '*/*',
    },
  },
  {
    id: '41k7q0j5fpi-req',
    protocol: 'http',
    requestId: '41k7q0j5fpi',
    timestamp: 1754640493259,
    method: 'GET',
    url: 'http://localhost:64436/socket.io/?EIO=4&transport=polling&t=jn9hn3s5&sid=5ZP0tYVNRx34yengAAAI',
    headers: {
      Accept: '*/*',
    },
  },
  {
    id: 'uzkwz4eq1mm-req',
    protocol: 'http',
    requestId: 'uzkwz4eq1mm',
    timestamp: 1754640493259,
    method: 'POST',
    url: 'http://localhost:64436/socket.io/?EIO=4&transport=polling&t=jn9hnpb5&sid=5ZP0tYVNRx34yengAAAI',
    headers: {
      'Content-type': 'text/plain;charset=UTF-8',
      Accept: '*/*',
    },
    body: '40',
  },
  {
    id: 'ji1gyzqfz2f-req',
    protocol: 'http',
    requestId: 'ji1gyzqfz2f',
    timestamp: 1754640493259,
    method: 'POST',
    url: 'http://localhost:64436/socket.io/?EIO=4&transport=polling&t=jn9hnpb5&sid=5ZP0tYVNRx34yengAAAI',
    headers: {
      'Content-type': 'text/plain;charset=UTF-8',
      Accept: '*/*',
    },
    body: '40',
  },
  {
    id: 'tnjfjsanhri-res',
    protocol: 'http',
    requestId: 'tnjfjsanhri',
    timestamp: 1754640493266,
    status: 200,
    statusText: 'OK',
    headers: {
      'cache-control': 'no-store',
      'content-length': '118',
      'content-type': 'text/plain; charset=UTF-8',
    },
    body: '0{"sid":"5ZP0tYVNRx34yengAAAI","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000}',
    delayMs: 16,
    isStream: false,
  },
  {
    id: '2fy8illlonc-res',
    protocol: 'http',
    requestId: '2fy8illlonc',
    timestamp: 1754640493271,
    status: 200,
    statusText: 'OK',
    headers: {
      'cache-control': 'no-store',
      'content-length': '118',
      'content-type': 'text/plain; charset=UTF-8',
    },
    body: '0{"sid":"5ZP0tYVNRx34yengAAAI","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000}',
    delayMs: 20,
    isStream: false,
  },
  {
    id: 'uzkwz4eq1mm-res',
    protocol: 'http',
    requestId: 'uzkwz4eq1mm',
    timestamp: 1754640493277,
    status: 200,
    statusText: 'OK',
    headers: {
      'cache-control': 'no-store',
      'content-length': '2',
      'content-type': 'text/html',
    },
    body: 'ok',
    delayMs: 18,
    isStream: false,
  },
  {
    id: 'ji1gyzqfz2f-res',
    protocol: 'http',
    requestId: 'ji1gyzqfz2f',
    timestamp: 1754640493283,
    status: 200,
    statusText: 'OK',
    headers: {
      'cache-control': 'no-store',
      'content-length': '2',
      'content-type': 'text/html',
    },
    body: 'ok',
    delayMs: 24,
    isStream: false,
  },
  {
    id: 'oln9r1jedcj-req',
    protocol: 'http',
    requestId: 'oln9r1jedcj',
    timestamp: 1754640493289,
    method: 'GET',
    url: 'http://localhost:64436/socket.io/?EIO=4&transport=polling&t=jn9ihb9e&sid=5ZP0tYVNRx34yengAAAI',
    headers: {
      Accept: '*/*',
    },
  },
  {
    id: 'dm8cb4qki7c-req',
    protocol: 'http',
    requestId: 'dm8cb4qki7c',
    timestamp: 1754640493289,
    method: 'GET',
    url: 'http://localhost:64436/socket.io/?EIO=4&transport=polling&t=jn9ihb9e&sid=5ZP0tYVNRx34yengAAAI',
    headers: {
      Accept: '*/*',
    },
  },
  {
    id: 'ehcx7tdmufr-s2c-1754640493289',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640493289,
    url: 'http://localhost:64436',
    direction: 'serverToClient',
    namespace: '/',
    event: 'connect',
    data: [],
  },
  {
    id: 's2xve134evj-res',
    protocol: 'http',
    requestId: 's2xve134evj',
    timestamp: 1754640493296,
    status: 200,
    statusText: 'OK',
    headers: {
      'cache-control': 'no-store',
      'content-length': '32',
      'content-type': 'text/plain; charset=UTF-8',
    },
    body: '40{"sid":"FAS24Tk2bbRqJoJ0AAAJ"}',
    delayMs: 37,
    isStream: false,
  },
  {
    id: '41k7q0j5fpi-res',
    protocol: 'http',
    requestId: '41k7q0j5fpi',
    timestamp: 1754640493303,
    status: 200,
    statusText: 'OK',
    headers: {
      'cache-control': 'no-store',
      'content-length': '32',
      'content-type': 'text/plain; charset=UTF-8',
    },
    body: '40{"sid":"FAS24Tk2bbRqJoJ0AAAJ"}',
    delayMs: 44,
    isStream: false,
  },
  {
    id: 'oln9r1jedcj-res',
    protocol: 'http',
    requestId: 'oln9r1jedcj',
    timestamp: 1754640493413,
    status: 200,
    statusText: 'OK',
    headers: {
      'cache-control': 'no-store',
      'content-length': '1',
      'content-type': 'text/plain; charset=UTF-8',
    },
    body: '6',
    delayMs: 124,
    isStream: false,
  },
  {
    id: 'dm8cb4qki7c-res',
    protocol: 'http',
    requestId: 'dm8cb4qki7c',
    timestamp: 1754640493419,
    status: 200,
    statusText: 'OK',
    headers: {
      'cache-control': 'no-store',
      'content-length': '1',
      'content-type': 'text/plain; charset=UTF-8',
    },
    body: '6',
    delayMs: 130,
    isStream: false,
  },
  {
    id: 'ehcx7tdmufr-c2s-1754640495489',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640495489,
    url: 'http://localhost:64436',
    direction: 'clientToServer',
    namespace: '/',
    event: 'hello',
    data: ['hello'],
  },
  {
    id: 'ehcx7tdmufr-s2c-1754640495497',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640495497,
    url: 'http://localhost:64436',
    direction: 'serverToClient',
    namespace: '/',
    event: 'response',
    data: [
      {
        message: '안녕하세요! 첫 번째 답장입니다.',
        timestamp: 1754640495490,
      },
    ],
  },
  {
    id: 'ehcx7tdmufr-s2c-1754640496492',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640496492,
    url: 'http://localhost:64436',
    direction: 'serverToClient',
    namespace: '/',
    event: 'response',
    data: [
      {
        message: '두 번째 답장입니다!',
        timestamp: 1754640496491,
      },
    ],
  },
  {
    id: 'ehcx7tdmufr-c2s-1754640499808',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640499808,
    url: 'http://localhost:64436',
    direction: 'clientToServer',
    namespace: '/',
    event: 'hello',
    data: ['hello'],
  },
  {
    id: 'ehcx7tdmufr-s2c-1754640499817',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640499817,
    url: 'http://localhost:64436',
    direction: 'serverToClient',
    namespace: '/',
    event: 'response',
    data: [
      {
        message: '안녕하세요! 첫 번째 답장입니다.',
        timestamp: 1754640499812,
      },
    ],
  },
  {
    id: 'usvxgppj2vp-req',
    protocol: 'http',
    requestId: 'usvxgppj2vp',
    timestamp: 1754640500687,
    method: 'GET',
    url: 'https://jsonplaceholder.typicode.com/posts/1',
  },
  {
    id: 'usvxgppj2vp-res',
    protocol: 'http',
    requestId: 'usvxgppj2vp',
    timestamp: 1754640500749,
    status: 200,
    statusText: '',
    headers: {
      'cache-control': 'max-age=43200',
      'content-type': 'application/json; charset=utf-8',
      expires: '-1',
      pragma: 'no-cache',
    },
    body: {
      userId: 1,
      id: 1,
      title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
      body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
    },
    delayMs: 62,
    isStream: false,
  },
  {
    id: 'ehcx7tdmufr-s2c-1754640500813',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640500813,
    url: 'http://localhost:64436',
    direction: 'serverToClient',
    namespace: '/',
    event: 'response',
    data: [
      {
        message: '두 번째 답장입니다!',
        timestamp: 1754640500813,
      },
    ],
  },
  {
    id: '1mi5nrf9inr-req',
    protocol: 'http',
    requestId: '1mi5nrf9inr',
    timestamp: 1754640501702,
    method: 'GET',
    url: 'https://jsonplaceholder.typicode.com/posts/1',
    headers: {
      Accept: 'application/json, text/plain, */*',
    },
  },
  {
    id: 'k51evva192m-req',
    protocol: 'http',
    requestId: 'k51evva192m',
    timestamp: 1754640501702,
    method: 'GET',
    url: 'https://jsonplaceholder.typicode.com/posts/1',
    headers: {
      Accept: 'application/json, text/plain, */*',
    },
  },
  {
    id: '1mi5nrf9inr-res',
    protocol: 'http',
    requestId: '1mi5nrf9inr',
    timestamp: 1754640501725,
    status: 200,
    statusText: '',
    headers: {
      'cache-control': 'max-age=43200',
      'content-type': 'application/json; charset=utf-8',
      expires: '-1',
      pragma: 'no-cache',
    },
    body: {
      userId: 1,
      id: 1,
      title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
      body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
    },
    delayMs: 23,
    isStream: false,
  },
  {
    id: 'k51evva192m-res',
    protocol: 'http',
    requestId: 'k51evva192m',
    timestamp: 1754640501732,
    status: 200,
    statusText: '',
    headers: {
      'cache-control': 'max-age=43200',
      'content-type': 'application/json; charset=utf-8',
      expires: '-1',
      pragma: 'no-cache',
    },
    body: {
      userId: 1,
      id: 1,
      title: 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
      body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
    },
    delayMs: 30,
    isStream: false,
  },
  {
    id: 'ehcx7tdmufr-c2s-1754640502629',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640502629,
    url: 'http://localhost:64436',
    direction: 'clientToServer',
    namespace: '/',
    event: 'hello',
    data: ['hello'],
  },
  {
    id: 'ehcx7tdmufr-s2c-1754640502648',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640502648,
    url: 'http://localhost:64436',
    direction: 'serverToClient',
    namespace: '/',
    event: 'response',
    data: [
      {
        message: '안녕하세요! 첫 번째 답장입니다.',
        timestamp: 1754640502633,
      },
    ],
  },
  {
    id: 'ehcx7tdmufr-s2c-1754640503635',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640503635,
    url: 'http://localhost:64436',
    direction: 'serverToClient',
    namespace: '/',
    event: 'response',
    data: [
      {
        message: '두 번째 답장입니다!',
        timestamp: 1754640503634,
      },
    ],
  },
  {
    id: 'ehcx7tdmufr-s2c-1754640505384',
    protocol: 'socketio',
    requestId: 'ehcx7tdmufr',
    timestamp: 1754640505384,
    url: 'http://localhost:64436',
    direction: 'serverToClient',
    namespace: '/',
    event: 'disconnect',
    data: ['io client disconnect', null],
  },
];
