nodeLinker: pnp
pnpMode: strict
enableGlobalCache: false
immutablePatterns:
  - "**/dist/**"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
